
# Kaldi compiled with static, no cuda and openblas for dynamic linking.
# kaldi.mk is generated by running ./configure below.
# openblas should be prepared before in ../tools.
./configure --static \
            --use-cuda=no \
            --mathlib=OPENBLAS --openblas-root=../tools/OpenBLAS/install \
            --threaded-math=no --static-math=yes \
            --static-fst=yes --fst-root=../tools/openfst

echo 'CXXFLAGS += -fPIC' >> kaldi.mk
